### ISSUE TITLE
[APIs] actions enhancements

### ISSUE THREAD

**Issue by Nishchit14** [firecampapp/firecamp-doc#10]
We can write the actions for the following features in Firecamp.

 - Securing your request with Authentication
 - Run GraphQL query
 - Play with protobuf request body and schema
 - Pre/Post script - Extends functionalities  with the script
 - How to write test cases? 

please share your suggestions @mehtavishwa30  @vipulgupta2048

**Comment by mehtavishwa30** [comment]
Hey @Nishchit14, I'll be taking up this issue and writing the suggested Actions. Let's set up a call tomorrow to help me understand these topics well enough to write them.

**Comment by Nishchit14** [comment]
closing it due to stale.
