### ISSUE TITLE
Better cross platform framework to build short video recording and editing app.

### ISSUE THREAD

**Issue by KRN05** [firecampapp/firecamp-doc#104]
I am planning to build a short video recording recording app and was wondering which would be better Flutter or React Native. I have researched a bit and found that react native supports many third party libraries for video recording whereas Flutter camera plugin is still under development. 

Please suggest which one should I pick considering the advanced features, flexibility, customization, and development time.

Thanks!

**Comment by Nishchit14** [comment]
No experience with Flutter. so can't help much. also, this is not a good place to ask this question. We have discord community you can ask there,
