### ISSUE TITLE
File description suggestions

### ISSUE THREAD

**Issue by Nishchit14** [firecampapp/firecamp-doc#11]
Instead of writing a long description we can just write a small description with clearer context. (like use how-to, intro, benefits phrases)

#### current
![image](https://user-images.githubusercontent.com/5078921/76936585-2d1a0400-6919-11ea-9e78-206c7e6aae1f.png)

#### suggestion
![image](https://user-images.githubusercontent.com/5078921/76936850-ac0f3c80-6919-11ea-9eb4-cbf525b9b9dc.png)

### Reference
https://docs.wpgraphql.com/

![image](https://user-images.githubusercontent.com/5078921/76936929-c8ab7480-6919-11ea-8511-abce03e36be8.png)

cc @vipulgupta2048 @mehtavishwa30

**Comment by vipulgupta2048** [comment]
Good work @Sc0rpi0n101, next when the GraphQL review is done. Then you can automatically solve that as well and open a PR for it.
