### ISSUE TITLE
[GraphQL] 03. Playground

### ISSUE THREAD

**Issue by Nishchit14** [firecampapp/firecamp-doc#25]
We can describe many small but effective features here in this Playground Impression.

 Like, we can write multiple numbers of queries/mutations/subscriptions in playground area, when we focus on the area of query It'll become an active query. also can explain the `prettify`, `reset` and `push to collection` buttons. same with `Q`, `M`, `S` buttons at the top right side. Variables/Files features.

![image](https://user-images.githubusercontent.com/5078921/78025337-805b7000-7377-11ea-9fdd-f66146948d33.png)

**Comment by vipulgupta2048** [comment]
For sure, I didn't have anything here because we actually tried showing their use in an Action. But, still a good to have feature.
