### ISSUE TITLE
[GraphQL] GraphQL Schema Doc

### ISSUE THREAD

**Issue by Nishchit14** [firecampapp/firecamp-doc#28]
Can we create a new impression for the GraphQL Schema Doc?

![image](https://user-images.githubusercontent.com/5078921/78026502-5e62ed00-7379-11ea-9e55-49dfddf944ea.png)

**Comment by vipulgupta2048** [comment]
Hey, @Nishchit14 I do need a bit of an assist in this. What exactly should I be writing about it? 
I mean, I can surely write about the feature being present and the oblivious stuff :sweat_smile: 
I just wanted to confirm if there is something more that you are looking forward to in this specific impression

**Comment by Nishchit14** [comment]
Actually, This is a schema documentation. which explains the GraphQL schema to developers. Like the skeleton of query/mutation/subscription, what response they will return and all. 

This imp[ression will be very small but still useful for a novice developer.  I'll extend it once you write about it. for more information, you can do a bit of research, so by reading you'll get a better idea and also try it in the Firecamp app so you'll feel the purpose.
