### ISSUE TITLE
Actions: reference links in Prerequisites

### ISSUE THREAD

**Issue by bistaastha** [firecampapp/firecamp-doc#30]
Actions are meant to guide a reader through a particular task, step by step.

So it makes sense that there should be more reference links to other parts of Firecamp documentation in the Prerequisite section of any Action.

[Example](https://github.com/firecampapp/firecamp-doc/blob/master/source/apis/actions/generating-code-snippets.mdx)

Here adding links would greatly clear up the context for someone going through the Action, and point them to things they need to do beforehand.

**Comment by vipulgupta2048** [comment]
+1 on this, I feel if we can shape up the Action prerequisites a little better and link them back to previous actions that are written, impressions or even external resources. Then, it would greatly help out the reader. At this point, it might be more confusing than helpful to readers who are absolute beginners to this. 

What do you think @mehtavishwa30

**Comment by vipulgupta2048** [comment]
@mehtavishwa30 As decided on the Discord conversations, can you help out Aastha with adding links to prereqs on this.
