### ISSUE TITLE
01. URLbar

### ISSUE THREAD

**Issue by Nishchit14** [firecampapp/firecamp-doc#4]
We can add the list of sub-elements in URLbar

1. Methods
2. URL 
3. Send button (Execute)
4. Save request
5. Environment badges

![image](https://user-images.githubusercontent.com/5078921/76854578-597c4480-6875-11ea-9330-952c51e4b1fe.png)

**Comment by Nishchit14** [comment]
cc @vipulgupta2048 @mehtavishwa30

**Comment by vipulgupta2048** [comment]
Gotcha! Thanks for opening the issue @Nishchit14. That sounds logical. 
Will edit all `URL Bar` impressions :heavy_check_mark: to be in the same format.

**Comment by vipulgupta2048** [comment]
I have named the 5 fields to keep in sync with what is being shown as 


The URL bar consists of 5 elements,
1. Method Selection
2. URL field
3. Send button (Execute)
4. Save button
5. Environment badges
