### ISSUE TITLE
02. Request Panel

### ISSUE THREAD

**Issue by Nishchit14** [firecampapp/firecamp-doc#5]
The overview has too many texts, we can reduce it, a developer loves less reading more bullets/sentences/images/code

We can show the list of inner components in `REQUEST PANEL`
```
1. Body
     - Quick method selection
     - Quick body type selection
     - plus icon for multiple body creation

2.  Auths
      - Quick auth type selection
3. Headers
4. Params
5. Scripts
    - pre
    - post
    - test script
6. Config
7. Code snippets preview 
```
![image](https://user-images.githubusercontent.com/5078921/76854840-d4455f80-6875-11ea-8132-7cb3d874c70e.png)

**Comment by vipulgupta2048** [comment]
Love it, totally agree. I just like to put all my thoughts that I have in the first draft and worry about optimization in the review. This helps.
