### ISSUE TITLE
03. Response Panel

### ISSUE THREAD

**Issue by Nishchit14** [firecampapp/firecamp-doc#6]
> The response panel in the Firecamp API app is to view, format and get more information about the response of your request.

Response panel is not something for formatting the information, Yes it's true we can prettify but this terminology is not proper for developer language. We can simply add one line like `The response payload can be folded, prettify and copies easily from utility icons shown in below image`

> The response body can be presented as JSON or text by clicking the toggle buttons below the Body tab. With the options to copy, fold as well as word wrap if needed, the API response body can be viewed, and formatted as needed.

This is not limited to only JSON/Text, Response body can be anything like HTML/Preview, JSON/XML/Text, Image/GIF anything. so we can change this paragraph accordingly.

> Response Headers provide information about the body and can be represented as the metadata for the response.

Can give small clarity in this sentence. `Response Headers provide information about the server's response which can also be represented as the metadata for the response.`

cc @vipulgupta2048 @mehtavishwa30

**Comment by vipulgupta2048** [comment]
Tick, @Nishchit14 you can check out the PR and suggest more changes as needed.
