### ISSUE TITLE
08. Auth Type Selection

### ISSUE THREAD

**Issue by Nishchit14** [firecampapp/firecamp-doc#8]
This is a part of the `Auth` section of the Request body.

We can create an individual doc file for Auth and include `Quick auth selection` under it. 

with the addition of that, we can add a small description of all the available auth types and its references for more learning.

Also, we can improve the overview paragraph with fewer texts and more context

cc @vipulgupta2048  @mehtavishwa30

**Comment by vipulgupta2048** [comment]
@Nishchit14 That was my inital idea, but like request methods. I didn't find one great place to get information on all auths used by Firecamp. Can you suggest a resource for the same?

**Comment by Nishchit14** [comment]
Sure,

https://blog.restcase.com/4-most-used-rest-api-authentication-methods/
https://developers.google.com/identity/protocols/oauth2 (depth case)
