### ISSUE TITLE
10. API endpoints

### ISSUE THREAD

**Issue by Nishchit14** [firecampapp/firecamp-doc#9]
1. It has more texts, (only texts) which makes boring feelings while reading. we can reduce them.
2. why this section needed? which part of the app it is representing? 
3. we can add small information about `10. API endpoints` in `URL bar` instead of creating individual (my suggestions)

cc @vipulgupta2048  @mehtavishwa30

**Comment by vipulgupta2048** [comment]
@Nishchit14  Even I am not sure why I have added something so general. Will remove it or if the content looks good will add it to the URL bar. 
Should I also remove GraphQL endpoints?

**Comment by Nishchit14** [comment]
Yes, we can add a small section in URLbar itself about the API endpoint if it makes sense with the flow.

**Comment by vipulgupta2048** [comment]
Oh this is done too. Closing.
